return {
    "folke/which-key.nvim",
    event = "VeryLazy",
    opts = {
        delay = 300,
        icons = {
            mappings = false,
            breadcrumb = "»",
            separator = "→",
            group = "+",
        },
        win = {
            border = "rounded",
            padding = { 1, 2 },
            wo = { winblend = 0 },
        },
        layout = {
            spacing = 4,
            align = "left",
        },
        spec = {
            { "<leader>f", group = "find" },
            { "<leader>g", group = "git" },
            { "<leader>s", group = "split" },
            { "<leader>l", group = "lsp" },
            { "<leader>S", group = "spell/grammar" },
            { "<leader>w", desc = "Save" },
            { "<leader>q", desc = "Quit" },
            { "<leader>Q", desc = "Quit all (force)" },
            { "<leader>ld", desc = "Line diagnostics" },
            { "<leader>lx", desc = "Toggle virtual text" },
            { "<leader>ll", desc = "Toggle hover float mode" },
            { "<leader>lr", desc = "Rename symbol" },
            { "<leader>la", desc = "Code action" },
            { "<leader>gs", desc = "Stage hunk" },
            { "<leader>gp", desc = "Preview hunk" },
            { "<leader>gb", desc = "Blame line" },
            { "<leader>gr", desc = "Reset hunk" },
            { "<leader>gd", desc = "Diff this" },
            { "<leader>St", desc = "Toggle spell check" },
            { "<leader>Sf", desc = "Fix suggestion" },
            { "<leader>Sa", desc = "Add word to dictionary" },
            { "<leader>Sx", desc = "Mark word as wrong" },
            { "<C-Up>", desc = "Resize split (up)" },
            { "<C-Down>", desc = "Resize split (down)" },
            { "<C-Left>", desc = "Resize split (left)" },
            { "<C-Right>", desc = "Resize split (right)" },
            { "]h", desc = "Next hunk" },
            { "[h", desc = "Prev hunk" },
            { "]f", desc = "Next function" },
            { "[f", desc = "Prev function" },
            { "]a", desc = "Next argument" },
            { "[a", desc = "Prev argument" },
            { "]d", desc = "Next diagnostic" },
            { "[d", desc = "Prev diagnostic" },
            { "]s", desc = "Next misspelled word" },
            { "[s", desc = "Prev misspelled word" },
        },
    },
}
